[package]
name = "bnf"
version = "0.1.2"
authors = ["Shea Newton"]

description = "A library for parsing Backus–Naur form context-free grammars"
readme = "README.md"
keywords = ["bnf"]

homepage = "https://github.com/snewt/bnf"
repository = "https://github.com/snewt/bnf"

license = "MIT"

[features]
unstable = []

[dependencies.stacker]
version = "0.1.2"

[dependencies.rand]
version = "0.3.17"

[dependencies.nom]
version = "^3.2"
features = ["verbose-errors"]
